### ISSUE TITLE
Suggestion: Install SSH client for r10k

### ISSUE THREAD

**Issue by blueback13** [voxpupuli/container-puppetserver#100]
Git and r10k are installed when building the Puppet server docker image, but no SSH client is included. This means that r10k can only be used with HTTPS repositories.

There are two options to enable SSH clients:
1. Install `openssh-client` with [the other dependency packages](https://github.com/voxpupuli/container-puppetserver/blob/638c71705e926919dce3cd8d7f855eb03794b405/puppetserver/Dockerfile#L10)
2. Install the `rugged` gem [when r10k is installed](https://github.com/voxpupuli/container-puppetserver/blob/638c71705e926919dce3cd8d7f855eb03794b405/puppetserver/Dockerfile#L112C5-L112C30)
3. Or install both `openssh-client` and `rugged`

**Comment by rwaffen** [comment]
@voxpupuli/tools-containerimages guys, what do you think? adding git, rugged or both, what's best?

**Comment by bastelfreak** [comment]
both have different benefits, so I think we should include both
