### ISSUE TITLE
Intermediate CA feature update broken

### ISSUE THREAD

**Issue by sbjzn** [voxpupuli/container-puppetserver#116]
Related commit: https://github.com/voxpupuli/container-puppetserver/commit/84f7d5c6a8fbe66254c17f2a05661d60f776fa16

This update appears to have several issues. 

1. The default setting is INTERMEDIATE_CA=false, however the check at https://github.com/voxpupuli/container-puppetserver/blob/2310dfd229a5b7c4e23d8fe48de3c6f95750650e/puppetserver/docker-entrypoint.d/90-ca.sh#L48 is wrong, it enables the intermediate_ca feature if the value is not true. it should be:
`if [[ "$INTERMEDIATE_CA" == "true" ]]; then`

2. Typo of intermediate here: https://github.com/voxpupuli/container-puppetserver/blob/2310dfd229a5b7c4e23d8fe48de3c6f95750650e/puppetserver/Dockerfile#L39

**Comment by zinkscott** [comment]
Seeing this as well.

**Comment by l4rsV** [comment]
If you restart the container, the 90.sh script crashes the startup, if you have already imported the CA earlier.
See attachment.
[puppet_intermediate.txt](https://github.com/user-attachments/files/16909070/puppet_intermediate.txt)

**Comment by rwaffen** [comment]
Please open a separate issue and reference this pr. this one here is closed and everything else will be handle in an new pr/issue. Thank you 🙏
