### ISSUE TITLE
Intermediate CA import crashes container Startup if CA is already imported

### ISSUE THREAD

**Issue by l4rsV** [voxpupuli/container-puppetserver#122]
If you restart the container, the 90.sh script crashes the startup, if you have already imported the CA earlier.
See attachment.

I think something like checking for existing files before importing ($ puppetserver ca import) could fix it or changing the exit code?

Reference: #116 

[puppet_intermediate.txt](https://github.com/user-attachments/files/16927745/puppet_intermediate.txt)

**Comment by rwaffen** [comment]
@tuxmea did you see something like this, while you implemented this?

**Comment by l4rsV** [comment]
I did a quick and dirty fix for our systems and override it by dockerfile. So container restarting isn't a problem anymore:

`    if [[ -f /etc/puppetlabs/puppet/ssl/certs/ca.pem ]]; then
      # alternativ
      # if ls /etc/puppetlabs/puppet/ssl/certs/*.pem
      echo 'Error: Puppetca already imported, delete first if you want to replace'
      exit 0
    else
       puppetserver ca import \
      --cert-bundle $INTERMEDIATE_CA_BUNDLE \
      --crl-chain $INTERMEDIATE_CRL_CHAIN \
      --private-key $INTERMEDIATE_CA_KEY
    fi
`
