### ISSUE TITLE
Container health-check fails after creating a certificate

### ISSUE THREAD

**Issue by AFAde** [voxpupuli/container-puppetserver#130]
Hi,
We ran the following command (within a running container) to generate a certificate for the Puppet board:

`puppetserver ca generate --certname $CERTNAME`

The issue is that the command saves the certificate to the ${SSLDIR}/certs folder, which causes the healthcheck.sh script to fail because the following line of code

`certname=$(cd "${SSLDIR}/certs" && ls *.pem | grep --invert-match ca.pem)`

cannot set the certname variable correctly. 

The only way to fix the problem was to remove the newly generated .pem certificate from the directory (which is fine anyway, as it seems that the certificate is also copied to the ca/signed directory).

Could you please take a look at that? Is that a bug in the healthcheck.sh script? Or could it be that we have a wrong setting in the puppet.conf file?

Thanks

**Comment by rwaffen** [comment]
Thanks for the issue. I‘m not happy myself with this code. Was wondering when it will break. I have several local test to enhance this. But didn’t feel ready yet.

**Comment by AFAde** [comment]
Hi, thanks for the quick reply. 

Well, I guess we have indeed broken it. Do you plan to fix it in a future release?

**Comment by rwaffen** [comment]
i'm right on it. have some time traveling. PR incomming!

**Comment by AFAde** [comment]
Thanks!
