### ISSUE TITLE
run puppet  generate types

### ISSUE THREAD

**Issue by rismoney** [voxpupuli/container-puppetserver#15]
I would like to be able to do something like this-
watch -n 60 'for subdir in /etc/puppetlabs/code/environments/*; do [ -d "$subdir" ] && puppet generate types --environment "$(basename "$subdir")"; done' &

Can we add this capability, since in container world, r10k shouldn't be an assumption.
Not sure how to add this.  Should cron be avail in container, and then add a job?

**Comment by tuxmea** [comment]
There is no need to run puppet generate types, as r10k can handle this internally.
https://github.com/puppetlabs/r10k/blob/main/doc/dynamic-environments/configuration.mkd#generate_types

**Comment by rismoney** [comment]
Not if you dont use r10k

**Comment by tuxmea** [comment]
> Not if you dont use r10k

That is correct. In this case you can put a droplet into `puppetserver/docker-custom-entrypoint.d/`.
But this means that you must recreate the container image.

Most customers have their Puppet code on a share and deploy it on the share using r10k.

**Comment by tuxmea** [comment]
We recommend to run the code deployment separate and not inside the puppetserver container.

**Comment by rismoney** [comment]
so if you run the code deployment separate outside the puppetserver container, how do you run the command puppet generate types?  Doesn't that cmd inherently require puppet???

**Comment by rismoney** [comment]
alright i will close this, as I was able to accomplish this in my cloning/stager tool, by installing puppet gem and associated gems used by types.
