### ISSUE TITLE
Puppetserver 8

### ISSUE THREAD

**Issue by ldaneliukas** [voxpupuli/container-puppetserver#16]
I can see that GitHub Actions workflow is prepared to release the Puppetserver 8 container - are there any obstacles that need to be solved before that can be done? Same for [PuppetDB 8](https://github.com/voxpupuli/container-puppetdb).

**Comment by rwaffen** [comment]
nope, we just didn't do it yet.
i will see if i find some time this week to build a v8 container and test it.

**Comment by rwaffen** [comment]
puppet 8 will be build automatically with #19

**Comment by rwaffen** [comment]
tagged releases will come like soon, `0.1.0-8`, but for the meantime you may use the tag `main-8`, which ist the latest build from main with puppet 8

**Comment by ldaneliukas** [comment]
Awesome, thanks!
