### ISSUE TITLE
Puppetserver container manifest unknown

### ISSUE THREAD

**Issue by mitchdubdub** [voxpupuli/container-puppetserver#17]
Received an error trying to pull the puppetserver container

```
podman image pull voxpupuli/container-puppetserver

Resolving "voxpupuli/container-puppetserver" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/voxpupuli/container-puppetserver:latest...
Error: initializing source docker://voxpupuli/container-puppetserver:latest: reading manifest latest in docker.io/voxpupuli/container-puppetserver: manifest unknown
```

**Comment by rwaffen** [comment]
ho hi, yes, this is a problem atm, we don't have a "latest" tag yet.
pls look here a grab a tag. the tagging will be reworked soon, and then there will also be a "latest" tag.
https://github.com/voxpupuli/container-puppetserver/pkgs/container/container-puppetserver

**Comment by rwaffen** [comment]
latest tag will be added with #19

**Comment by rwaffen** [comment]
latest tag is now available, but check in the container releases to which build (7 or 8) it refers.

**Comment by mitchdubdub** [comment]
thank you for fixing this
