### ISSUE TITLE
container build is breaking

### ISSUE THREAD

**Issue by rwaffen** [voxpupuli/container-puppetserver#47]
```
46.99 ERROR:  Error installing r10k:
46.99 	The last version of faraday-net_http (>= 2.0, < 3.2) to support your Ruby & RubyGems was 3.0.2. Try installing it with `gem install faraday-net_http -v 3.0.2` and then running the current command again
46.99 	faraday-net_http requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```

see https://github.com/voxpupuli/container-puppetserver/actions/runs/7478099037/job/20352284695?pr=46

**Comment by rwaffen** [comment]
r10k dependency is breaking. gem command is automatically used from the puppet-agent environment. 

- we could switch to the packaged r10k. but this would mean going back to version 3.7.x
- we could try to install system ruby which is >=3.x.y

@tuxmea @bastelfreak whats you opinion?

**Comment by tuxmea** [comment]
Would it be possible to first install `faraday-net_http` in Version 3.0.2. and the install r10k?
Or maybe make Gemfile.lock part of the repo?
