### ISSUE TITLE
Add support for certname parameter

### ISSUE THREAD

**Issue by mdechiaro** [voxpupuli/container-puppetserver#51]
The `certname` and `server` name as set to `PUPPETSERVER_HOSTNAME` in [docker-entrypoint.d/50-set-certname.sh](https://github.com/voxpupuli/container-puppetserver/blob/main/puppetserver/docker-entrypoint.d/50-set-certname.sh#L4-L5). It would be useful if these could be declared separately. An example would be to have multiple puppetservers behind a load balancer. The `certname` would be the `fqdn` of each server, and the `server` parameter would match the load balancer `fqdn`. Each node would have the load balancer `fqdn` setup as a `dns_alt_name`.

**Comment by rwaffen** [comment]
I think the $CERTNAME isn't needed here. The `server` parameter isn't used inside the container. It would be interesting for a normal compiler with an own agent, but in the container there is no agent running. It is installed, but not used for the puppetserver. It is from an older version, when Puppet Inc. itself maintained this repo, but I see no benefit now in keeping this.

so the hostname and dns_alt_names is sufficient for a ha setup. 🤔 

it tested this already and have a PR open at crafty https://github.com/voxpupuli/crafty/pull/29

is this the thing you also wanted to do? Is this enough or did i miss something?

**Comment by mdechiaro** [comment]
> it tested this already and have a PR open at crafty https://github.com/voxpupuli/crafty/pull/29

Thanks for sharing that HA example. I am also doing something similar but with k8s using [minikube](https://github.com/mdechiaro/minikube-puppet-stack/blob/main/puppet/puppetserver.yaml). It's a currently a work in progress, and I was leveraging puppet to do the csr_attributes.yaml + autosign handshake in the container. If you go this route, then you don't have to manage the ssl certs outside of it.

> It is installed, but not used for the puppetserver. It is from an older version, when Puppet Inc. itself maintained this repo, but I see no benefit now in keeping this.

I see it being useful as it would minimize the amount of data that needs to be managed and mounted outside the container.

**Comment by rwaffen** [comment]
in regards of the `certname`, is here still something to do? otherwise i would close this issue?

**Comment by mdechiaro** [comment]
Yes, I think this parameter is useful and would like to use it.

**Comment by rwaffen** [comment]
a bit late, but here you go 😅
