### ISSUE TITLE
Allow setting of environment_timeout

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/container-puppetserver#67]
The default value is 0.
We want to be able to set the puppet config entry (via `puppet config set`) e.g. to unlimited.

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/container-puppetserver/blob/main/puppetserver/docker-entrypoint.d/83-environment-cache.sh we do this, but in the wrong section. Master is deprecated, it should be main or server.

**Comment by rwaffen** [comment]
what is best? main or server?

**Comment by tuxmea** [comment]
This setting is used by the server. so please add it to server section.
