### ISSUE TITLE
PUPPETSERVER_HOSTNAME is not unset

### ISSUE THREAD

**Issue by khenriks** [voxpupuli/container-puppetserver#71]
According to the documentation, `PUPPETSERVER_HOSTNAME` is supposed to be unset, but in fact the container explicitly sets it to `puppet`. This appears to be due to https://github.com/voxpupuli/container-puppetserver/blob/main/puppetserver/Dockerfile#L26. This also breaks compatibility with the old Puppet Labs-maintained images. I had to explicitly unset it myself in my docker compose file.

**Comment by rwaffen** [comment]
thx for the hint. which puppetlabs maintained containers do you mean? as far as i know we have this containers here, because they dont't maintain theirs anymore. (to be more precise they handed this repo over to us, so we could care about)

**Comment by khenriks** [comment]
I'm referring to the original images, as in https://hub.docker.com/r/puppet/puppetserver. My point is that if you're migrating from the old images to these ones, it doesn't work properly, because of the aforementioned issue with `PUPPETSERVER_HOSTNAME`.

**Comment by rwaffen** [comment]
oh, okay, now i see. will check the code for it and make a fix

**Comment by khenriks** [comment]
Thanks for the quick fix!
