### ISSUE TITLE
certfile selection fails if multiple certificates do exist

### ISSUE THREAD

**Issue by hadmut** [voxpupuli/container-puppetserver#90]
Hi,

just ran into a bug in /docker-entrypoint.d/99-log-config.sh :

If environment CERTNAME is not set, it does

else
  echo "* CERTNAME: unset"
  certname=$(cd "${SSLDIR}/certs" && ls *.pem | grep --invert-match ca.pem)
fi

but if there is more than just a single certificate (for some reason, it created a new certificate when run today), the variable certname is set to a concatenation of file names separated with a space or new line. 

e.g. if there is puppet.pem and puppet.fritz.box.pem, certname is set to 

"puppet.pem puppet.fritz.box.pem"

subsequently it outputs

 * Certname: 'puppet.fritz.box.pem
puppet.pem'

(Note that it outputs two file names separated by new line)

and eventually fails:

Certificate puppet.fritz.box.pem
puppet.pem:
Could not open file or uri for loading certificate from /etc/puppetlabs/puppet/ssl/certs/puppet.fritz.box.pem
puppet.pem

(Again: the processed file name consists of the concatenation of all file names, and thus does not work). 

Better: use something like find -type f -name '*.pem' ! -name ca.pem |head -1  and check, whether something has been found at all. 

Workaround: Set environment CERTNAME

regards

**Comment by datorr2** [comment]
I too had the same problem once I generated a certificate for `puppetboard`.

Workaround bypasses the issue.

**Comment by rwaffen** [comment]
thx for the issue, PR is on the way.
