### ISSUE TITLE
Security problem: autosign

### ISSUE THREAD

**Issue by hadmut** [voxpupuli/container-puppetserver#95]
Hi, 

puppetserver/Dockerfile has a command 

puppet config set autosign true --section master

and at runtime 
puppetserver/docker-entrypoint.d/60-setup-autosign.sh 
runs

if test -n "${AUTOSIGN}" ; then
  puppet config set autosign "$AUTOSIGN" --section master
fi

So if the variable  AUTOSIGN has not been set, the server is configured to allow autosign without admin's agreement, which is a severe security problem if puppet installes credentials on the client.

**Comment by rwaffen** [comment]
thx for the issue, PR is on the way
